services:
  postgres:
    image: postgis/postgis:15-3.3
    container_name: aegisflood_postgres
    environment:
      POSTGRES_DB: aegisflood_mvp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: aegisflood_api
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:password@postgres:5432/aegisflood_mvp
      - JWT_SECRET=change_me
      - FRONTEND_ORIGIN=http://localhost:5173
      - TWILIO_ACCOUNT_SID=
      - TWILIO_AUTH_TOKEN=
      - TWILIO_PHONE_NUMBER=
      - TWILIO_MOCK=true
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/backend

volumes:
  postgres_data:


